version: "3.0"

services:
  kali:
    build: .
    container_name: custom-kali-meta:tag
    ports: 
      - 13389:13389
      - 20022:20022
      - 5908:5908
      - 55510:80 
    volumes:
      - ./kali/:/home/trustworthy
    command: /bin/sh
  meta:
    image: raviprakash1907/custom-kali-linux:meta