name: custom-kali-linux:meta

on:
  push:
    branches: [ "meta/tag" ]
  pull_request:
    branches: [ "meta/tag" ]
  push:
    branches: [ "default/tag" ]
  pull_request:
    branches: [ "default/tag" ]
  schedule:
    - cron: "0 0 1 1/3 *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Updates Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push the Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/custom-kali-linux:meta
